package lib

type procedure string

const (
	Nop     procedure = "Nop"
	Jp      procedure = "Jp"
	Jr      procedure = "Jr"
	Di      procedure = "Di"
	Ld8     procedure = "Ld8"
	Ld16    procedure = "Ld16"
	Ldh     procedure = "Ldh"
	LdSPn   procedure = "LDSp+n"
	Push    procedure = "Push"
	Pop     procedure = "Pop"
	Call    procedure = "Call"
	Ret     procedure = "Ret"
	Reti    procedure = "Reti"
	Rst     procedure = "Rst"
	Inc     procedure = "Inc"
	Dec     procedure = "Dec"
	Add     procedure = "Add"
	AddHl   procedure = "AddHl"
	Add16_8 procedure = "Add16_8"
	Adc     procedure = "Adc"
	Sub     procedure = "Sub"
	Sbc     procedure = "Sbc"
	And     procedure = "And"
	Xor     procedure = "Xor"
	Or      procedure = "Or"
	Cp      procedure = "Cp"
	Cb      procedure = "Cb"
	Rlca    procedure = "Rlca"
	Rrca    procedure = "Rrca"
	Stop    procedure = "Stop"
	Rla     procedure = "Rla"
	Rra     procedure = "Rra"
	Daa     procedure = "Daa"
	Cpl     procedure = "Cpl"
	Scf     procedure = "Scf"
	Ccf     procedure = "Ccf"
	Ei      procedure = "Ei"
	Halt    procedure = "Halt"
)
